// <auto-generated />
using AplicationCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TenisChallenge.WebApi.Migrations
{
    [DbContext(typeof(PlayersContext))]
    [Migration("20250117043834_Fix_DataModel")]
    partial class Fix_DataModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AplicationCore.Entities.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ability")
                        .HasColumnType("integer")
                        .HasColumnName("ability");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("AplicationCore.Entities.FemalePlayers", b =>
                {
                    b.HasBaseType("AplicationCore.Entities.Players");

                    b.Property<double>("ReactionTime")
                        .HasColumnType("double precision")
                        .HasColumnName("reaction_time");

                    b.ToTable("female_players", (string)null);
                });

            modelBuilder.Entity("AplicationCore.Entities.MalePlayers", b =>
                {
                    b.HasBaseType("AplicationCore.Entities.Players");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<double>("Strengh")
                        .HasColumnType("double precision")
                        .HasColumnName("strengh");

                    b.ToTable("male_players", (string)null);
                });

            modelBuilder.Entity("AplicationCore.Entities.FemalePlayers", b =>
                {
                    b.HasOne("AplicationCore.Entities.Players", null)
                        .WithOne()
                        .HasForeignKey("AplicationCore.Entities.FemalePlayers", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AplicationCore.Entities.MalePlayers", b =>
                {
                    b.HasOne("AplicationCore.Entities.Players", null)
                        .WithOne()
                        .HasForeignKey("AplicationCore.Entities.MalePlayers", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
